#!/usr/bin/python3

# The daemon that must be killed; it sleeps a while and then randomly
# prints crud on the screen

import random
import time

def put_cursor(row,col):
  print(f"\033[{row};{col}H",end="")

def freakout():
  for i in range(30):
    row = random.randrange(40)
    col = random.randrange(60)
    put_cursor(row,col)
    time.sleep(0.2 - i/30*0.19)
    print("Nuwonmai!",end="",flush=True)
  put_cursor(30,0)
  # ascii art by Deelkar: https://www.asciiart.eu/mythology/devils
  daemon='''
.-._                                                   _,-,
  `._`-._                                           _,-'_,'
     `._ `-._                                   _,-' _,'
        `._  `-._        __.-----.__        _,-'  _,'
           `._   `#==="""           """===#'   _,'
              `._/)  ._               _.  (\\_,'
               )*'     **.__     __.**     '*( 
               #  .==..__  ""   ""  __..==,  # 
               #   `"._(_).       .(_)_."'   #
'''
  print(daemon,end="",flush=True)
  print("=====================================================================")
  print("= PRESS Ctl-L to refresh the screen and remove daemonic defacements =")
  print("=====================================================================")

def main():
  time.sleep(15)
  freakout()
  while True:
    # time.sleep(10)
    time.sleep(10*60)
    freakout()

main()

           
    
