#!/usr/bin/python3

# The daemon that must be killed; it sleeps a while and then randomly
# prints crud on the screen

import random
import time
import signal


def put_cursor(row,col):
  print(f"\033[{row};{col}H",end="")

def printstr_pos(string,startrow):
  '''Uses terminal cursor positioning to print a message.

  Without position, programs like vi / nano / less screw up the
  printing of newline-based messages; this funciton prevents that

  '''
  for (i,line) in enumerate(string.splitlines()):
    put_cursor(startrow+i,0)
    print(line,end="",flush=True)

def freakout():
  for i in range(40):
    row = random.randrange(40)
    col = random.randrange(60)
    put_cursor(row,col)
    time.sleep(0.2 - i/40*0.19)
    print("Nuwonmai!",end="",flush=True)
  # ascii art by Deelkar: https://www.asciiart.eu/mythology/devils
  message='''\
.-._                                                   _,-,          
  `._`-._                                           _,-'_,'          
     `._ `-._                                   _,-' _,'             
        `._  `-._        __.-----.__        _,-'  _,'                
           `._   `#==="""           """===#'   _,'                   
              `._/)  ._               _.  (\\_,'                     
               )*'     **.__     __.**     '*(                       
               #  .==..__  ""   ""  __..==,  #                       
               #   `"._(|).       .(|)_."'   #                       
=====================================================================
= PRESS Ctl-L to refresh the screen and remove daemonic defacements =
=====================================================================
'''
  printstr_pos(message,0)



def sighandler(signum,stackframe):
  for i in range(40):
    row = random.randrange(40)
    col = random.randrange(60)
    put_cursor(row,col)
    time.sleep(0.1 - i/40*0.09)
    print("Ha ha ha!",end="",flush=True)

  msg='''
=====================================================================
=           MWAH HA HA HA!      ,    ,    /\\   /\\                   =
=           I laugh at your    /( /\\ )\\  _\\ \\_/ /_                  =
=           pitiful signal,    |\\_||_/| < \\_   _/ >                 =
=           puny paladin.      \\______/  \\|0   0|/                  =
=                                _\\/_   _(_  ^  _)_                 =
=           It will take more   ( () ) /`\\|V"""V|/`\\                =
=           than that feeble      {}   \\  \\_____/  /                =
=           attempt to -KILL me!  ()   /\\   )=(   /\\                =
=           ---- DAEMON ----      {}  /  \\_/\\=/\\_/  \\               =
=====================================================================
= PRESS Ctl-L to refresh the screen and remove daemonic defacements =
=====================================================================
'''
  printstr_pos(msg,1)

def main():
  for s in signal.Signals:
    # if not s in {signal.SIGKILL, signal.SIGSTOP, signal.SIGSTP}:
    if not s in {9, 19, 20}:    # KILL, STOP, STP
      signal.signal(s, sighandler)

  time.sleep(15)
  freakout()
  while True:
    # time.sleep(10)
    time.sleep(10*60)
    freakout()

main()

           
    
