FROM debian:12-slim

ARG TARGETARCH

# re-enables man pages for install
RUN sed -i '/path-exclude \/usr\/share\/man/d' /etc/dpkg/dpkg.cfg.d/docker
RUN sed -i '/path-exclude \/usr\/share\/groff/d' /etc/dpkg/dpkg.cfg.d/docker

# update packages
RUN apt-get update

# reinstall some packages to get the manual pages
RUN apt-get install --reinstall \
    coreutils grep findutils diffutils bash

# install additional packages needed in the tutorial
RUN apt-get install -y \
    procps \
    file zip \
    tmux screen w3m \
    python3 gawk \
    which less \
    nano vim \
    python3 gawk wget curl \
    screen tmux man

# # uncomment to enable emacs in the build
# RUN apt install emacs-nox

# copy files over
COPY daemon /daemon
RUN chmod u+x daemon
COPY setup-files /setup-files
COPY main.sh /main.sh
RUN chmod u+x main.sh

CMD ./main.sh


