#!/bin/bash
# Old version of daemon that simply prints a message

sleep_secs=1000
message="The daemon lives...."

# sleep 10

while true; do
    sleep $sleep_secs
    echo $message

    # echo "$message"
    # echo "$message" | wall      # doesn't work due to docker not maintaining a login
done
